name: Coverage Report
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7

      - name: Set up cache
        uses: actions/cache@v2.1.5
        with:
          path: .venv
          key: venv-3.7-${{ hashFiles('requirements.txt') }}-${{ hashFiles('dev-requirements.txt') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install virtualenv
          virtualenv .venv
          source .venv/bin/activate
          pip install -r dev-requirements.txt

      - name: Generate coverage report
        run: |
          source ".venv/bin/activate"
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          files: ./coverage1.xml,./coverage2.xml
          directory: ./coverage/reports/
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.gz
          verbose: true
